apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitbucket
    application: bitbucket
  name: bitbucket
spec:
  ports:
    - name: web
      port: 7990
      protocol: TCP
      targetPort: 7990
  selector:
    app: atlassian
    application: bitbucket
  type: ClusterIP
