apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitbucket
    application: jira
  name: jira
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: atlassian
    application: jira
  type: ClusterIP
